---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 07/12/2020 18:01
---

Citizen.CreateThread(function()

    --[[
    LiteMySQL:Query():Select('players'):Insert({
        license = "Grolyptus",
        first_name = "Grolyptus",
        last_name = "Grolyptus",
        date_of_birth = "Grolyptus",
        nationality = "Grolyptus",
        sex = "Grolyptus",
    })
    ]]--

    --[[
    LiteMySQL:Query():Where("license", "=", "Anal"):CreateOrUpdate({
        license = "Anal",
        first_name = "Dylan",
        last_name = "Dylan",
        date_of_birth = "Dylan",
        nationality = "Ma bite",
        sex = "Dylan",
    })
    ]]--

    --local count = LiteMySQL:Query():Select('players'):Count();
    --print(count);

    --local count, result = LiteMySQL:Query('vSql'):Select('players'):Where('license', '=', 'placeholder'):Get();
    --print(count, json.encode(result))


    --local count = LiteMySQL:Query('vSql'):Select('players'):Where('license', '=', 'placeholder'):Count();
    --print(count)

    --local exists = LiteMySQL:Query('mysql-async'):Select('players'):Where('license', '=', 'placeholder'):Exists();
    --print(exists)


    --[[
    local count, result = LiteMySQL:Query():Select('players'):Where("license", "=", "groliptus"):CreateOrGet({
        license = "Groliptus",
        first_name = "Groliptus",
        last_name = "Groliptus",
        date_of_birth = "Groliptus",
        nationality = "Groliptus",
        sex = "Groliptus",
    })
    ]]--

    --[[
      local affectedRow = LiteMySQL:Query('mysql-async'):Select('players'):Where('license', '=', 'placeholder'):Update({
         license = "placeholder",
         first_name = "Dylan",
     });
     print(affectedRow)
     ]]--

    --local deleted = LiteMySQL:Query('mysql-async'):Select('players'):Where('license', '=', 'placeholder'):Delete();
    --print(deleted)

    --[[
    LiteMySQL.Schema:table('players', function(blueprint)
        blueprint:id();

        blueprint:string('license'):unique();
        blueprint:string('first_name'):length(255);
        blueprint:string('last_name'):length(255);
        blueprint:string('date_of_birth'):length(255);
        blueprint:string('nationality'):length(255);
        blueprint:string('sex'):length(255):default('Helicopter');

        blueprint:timestamps(); -- created_at, updated_at
    end)
    ]]--

end)

