---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 07/12/2020 18:01
---

Citizen.CreateThread(function()
    local count, result = LiteMySQL:Query('vSql'):Select('players'):Where('license', '=', 'placeholder'):Get();
    --print(count, json.encode(result))


    --local count = LiteMySQL:Query('vSql'):Select('players'):Where('license', '=', 'placeholder'):Count();
    --print(count)

    --local exists = LiteMySQL:Query('mysql-async'):Select('players'):Where('license', '=', 'placeholder'):Exists();
    --print(exists)

    --[[
    LiteMySQL.Schema:ta
    ble('players', function(blueprint)
        blueprint:id();

        blueprint:string('license'):unique();
        blueprint:string('first_name'):length(255);
        blueprint:string('last_name'):length(255);
        blueprint:string('date_of_birth'):length(255);
        blueprint:string('nationality'):length(255);
        blueprint:string('sex'):length(255):default('Helicopter');

        blueprint:timestamps(); -- created_at, updated_at
    end)
    ]]--
end)

